// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SomeReallyComplexProject.EntityFramework.DomainEvents;

namespace SomeReallyComplexProject.EntityFramework.DomainEvents.Migrations
{
    [DbContext(typeof(DomainEventsDbContext))]
    partial class DomainEventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SomeReallyComplexProject.EntityFramework.DomainEvents.DomainEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorrelationId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("EventData")
                        .IsRequired();

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsHandled");

                    b.Property<bool>("IsUndone");

                    b.Property<int>("Iteration");

                    b.HasKey("EventId");

                    b.ToTable("DomainEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
